name: covid19
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py37hf985489_0
  - argon2-cffi=20.1.0=py37h4b544eb_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=2.17=openblas
  - bleach=3.2.1=pyh9f0ad1d_0
  - ca-certificates=2020.12.5=h033912b_0
  - certifi=2020.12.5=py37hf985489_0
  - cffi=1.14.4=py37hc5b2277_1
  - cvxopt=1.2.0=py37ha78f441_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=h0c50699_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.2.9=hb1e8313_2
  - fftw=3.3.8=nompi_h27769e0_1114
  - freetype=2.10.4=h3f75d11_0
  - gettext=0.19.8.1=h7937167_1005
  - glib=2.66.3=h519c658_1
  - glpk=4.65=h343d7f2_1003
  - gmp=6.2.1=h2e338ed_0
  - gsl=2.4=ha2d443c_1006
  - icu=67.1=hb1e8313_0
  - importlib-metadata=3.1.1=pyhd8ed1ab_0
  - importlib_metadata=3.1.1=hd8ed1ab_0
  - ipykernel=5.3.4=py37he01cfaa_1
  - ipython=7.19.0=py37he01cfaa_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jedi=0.17.2=py37hf985489_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.17.0=py_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.0=py37hf985489_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.3.1=py37h8ec247f_0
  - krb5=1.17.2=h60d9502_0
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=10.0.1=default_hf57f61e_1
  - libcxx=11.0.0=h4c3b8ed_1
  - libedit=3.1.20191231=h0678c8f_2
  - libffi=3.3=h74dc148_1
  - libgfortran=4.0.0=h50e675f_13
  - libgfortran4=7.5.0=h50e675f_13
  - libglib=2.66.3=h60154bc_1
  - libiconv=1.16=haf1e3a3_0
  - liblapack=3.8.0=17_openblas
  - liblapacke=3.8.0=17_openblas
  - libllvm10=10.0.1=h009f743_3
  - libopenblas=0.3.10=openmp_h63d9170_5
  - libpng=1.6.37=h7cec526_2
  - libpq=12.3=haa216e0_2
  - libsodium=1.0.18=hbcb3906_1
  - llvm-openmp=11.0.0=h73239a0_1
  - lz4-c=1.9.2=hb1e8313_3
  - markupsafe=1.1.1=py37h395d20d_2
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py37hddda452_1
  - metis=5.1.0=h2e338ed_1006
  - mistune=0.8.4=py37h4b544eb_1002
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hfb8f7af_2
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37hf985489_3
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - notebook=6.1.5=py37hf985489_0
  - nspr=4.29=hb1e8313_1
  - nss=3.47=hc0980d9_0
  - openssl=1.1.1h=haf1e3a3_0
  - packaging=20.7=pyhd3deb0d_0
  - pandas=1.1.3=py37hdadc0f0_0
  - pandoc=2.11.2=hc929b4f_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - patsy=0.5.1=py_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=20.3.1=pyhd8ed1ab_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.8=pyha770c72_0
  - prompt_toolkit=3.0.8=hd8ed1ab_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.2=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h25ebb8a_4
  - pyrsistent=0.17.3=py37h4b544eb_1
  - python=3.7.8=h4f09611_3_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.4=pyhd8ed1ab_0
  - pyzmq=20.0.0=py37h47fd9b3_1
  - qt=5.12.9=h717870c_0
  - qtconsole=5.0.1=pyhd8ed1ab_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h0678c8f_2
  - scikit-learn=0.23.1=py37hf5857e7_0
  - scipy=1.5.1=py37hce1b9e5_0
  - seaborn=0.11.0=h694c41f_1
  - seaborn-base=0.11.0=pyhd8ed1ab_1
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37h2987424_2
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h17101e1_0
  - suitesparse=5.7.2=h0e59142_0
  - tbb=2019.9=ha1b3eb9_1
  - terminado=0.9.1=py37hf985489_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_1
  - tornado=6.1=py37h4b544eb_0
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.1=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py37hf985489_4
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.3=h74dc148_3
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.5=h289c70a_2
  - pip:
    - chardet==3.0.4
    - cython==0.29.17
    - idna==2.10
    - numpy==1.19.4
    - pmdarima==1.5.2
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - requests==2.25.0
    - statsmodels==0.12.1
    - urllib3==1.26.2
